version: '3.8'
services:
  devcontainer:
    build: .
    # can run `devcontainer-info content-url` in codespaces to see what image base is
    volumes:
      - ..:/workspaces/copier-python-package-template:cached
    command: sleep infinity
    ports:
      - "55874:2222"
    environment:
      - AWS_PROFILE=localstack
