name: Pre-commit

on:
  workflow_call:
    inputs:
      python-version:
        description: 'What version of python'
        type: string
        required: true
      setup-node:
        description: 'Whether to set up Node'
        type: boolean
        default: false
      node-version:
        description: 'What version of node'
        type: string
        required: false
        default: 'notUsing'

env:
  PYTHONUNBUFFERED: True
  PRE_COMMIT_HOME: ${{ github.workspace }}/.precommit_cache

permissions:
    contents: write # needed for mutex

jobs:
  pre-commit:
    runs-on: ubuntu-24.04
    name: Pre-commit
    steps:
      - name: Checkout code during push
        if: ${{ github.event_name == 'push' }}
        uses: actions/checkout@v4.2.2
        with:
          ref: ${{ github.ref_name }} # explicitly get the head of the branch, which will include any new commits pushed if this is a dependabot branch

      - name: Checkout code not during push
        if: ${{ github.event_name != 'push' }}
        uses: actions/checkout@v4.2.2

      - name: Install latest versions of  packages
        uses: ./.github/actions/install_deps
        with:
          python-version: ${{ inputs.python-version }}
          node-version: ${{ inputs.node-version }}

      - name: Set up mutex # Github concurrency management is horrible, things get arbitrarily cancelled if queued up. So using mutex until github fixes itself. When multiple jobs are modifying cache at once, weird things can happen.  possible issue is https://github.com/actions/toolkit/issues/658
        if: ${{ runner.os != 'Windows' }} # we're just gonna have to YOLO on Windows, because this action doesn't support it yet https://github.com/ben-z/gh-action-mutex/issues/14
        uses: ben-z/gh-action-mutex@1ebad517141198e08d47cf72f3c0975316620a65 # v1.0.0-alpha.10
        with:
          branch: mutex-venv-ubuntu-24.04-py${{ inputs.python-version }}-nodejs-${{ inputs.node-version }}
        timeout-minutes: 30 # this is the amount of time this action will wait to attempt to acquire the mutex lock before failing, e.g. if other jobs are queued up in front of it

      - name: Cache Pre-commit hooks
        uses: actions/cache@v4.2.3
        env:
          cache-name: cache-pre-commit-hooks
        with:
          path: ${{ env.PRE_COMMIT_HOME }}
          key: ubuntu-24.04-py${{ inputs.python-version }}-node-${{ inputs.node-version}}-${{ env.cache-name }}-${{ hashFiles('.pre-commit-config.yaml') }}
          restore-keys: |
            ubuntu-24.04-py${{ inputs.python-version }}-node-${{ inputs.node-version}}-${{ env.cache-name }}-

      - name: Run pre-commit
        run:  pre-commit run -a
